name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"
      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Update README.md
        uses: EndBug/add-and-commit@v4
        with:
          author_name: tamnk74
          author_email: khac.tam.94@gmail.com
          message: "Update README"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
